apiVersion: apps/v1
kind: Deployment
metadata:
  name: dealership
spec:
  replicas: 1
  selector:
    matchLabels:
      run: dealership
  template:
    metadata:
      labels:
        run: dealership
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: dealership
          image: us.icr.io/sn-labs-oaboushousha/dealership:latest
          ports:
            - containerPort: 8000
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
